---
name: 'Clean Repo'
description: 'Removes stale branches, PRs and issues'

inputs:
  token:
    description: 'Github token'
    required: true
  days-before-branch-stale:
    description: Number of days before branch is marked stale
    default: '120'
    required: false
  days-before-branch-delete:
    description: Number of days before branch is deleted
    default: '180'
    required: false
  days-before-pr-stale:
    description: Number of days before PR or issue is marked stale
    default: '60'
    required: false
  days-before-pr-close:
    description: Number of days before stale PR is closed
    default: '7'
    required: false
  days-before-issue-close:
    description: Number of days before stale issue is closed
    default: '7'
    required: false

runs:
  using: "composite"
  steps:
    - name: Clean issues and PRs
      id: stale_issues_prs
      uses: actions/stale@v9.0.0
      with:
        repo-token: ${{ inputs.token }}
        stale-issue-message: 'This issue is stale because it has been open ${{ inputs.days-before-pr-stale }} days with no activity. Remove stale label or comment or this will be closed in ${{ inputs.days-before-pr-delete }} days'
        stale-pr-message: 'This PR is stale because it has been open ${{ inputs.days-before-pr-stale }} days with no activity. Remove stale label or comment or this will be closed in ${{ inputs.days-before-pr-delete }} days'
        close-issue-message: 'This issue was closed due to inactivity.'
        close-pr-message: 'This PR was closed due to inactivity.'
        days-before-stale: ${{ inputs.days-before-pr-stale }}
        days-before-pr-close: ${{ inputs.days-before-pr-close }}
        days-before-issue-close: ${{ inputs.days-before-issue-close }}
        exempt-pr-labels: 'stale-exempt'
        exempt-issue-labels: 'stale-exempt'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        remove-issue-stale-when-updated: true
        remove-pr-stale-when-updated: true
        exempt-all-milestones: true
    
    - name: Print stale/closed Issues and PRs
      shell: bash
      env:
        ISSUES_PRS: ${{ join(steps.cleanup_issues_prs.outputs.*, ',') }}
      run: |
        echo "${ISSUES_PRS}"
        if [ -f "${GITHUB_STEP_SUMMARY}" ]; then
          echo "${ISSUES_PRS}" >> "${GITHUB_STEP_SUMMARY}"
        fi

    - name: Clean branches
      id: cleanup_branches
      uses: crs-k/stale-branches@v3.1.3
      with:
        repo-token: ${{ inputs.token }}
        days-before-stale: ${{ inputs.days-before-branch-stale }}
        days-before-delete: ${{ inputs.days-before-branch-delete }}
        comment-updates: false
        max-issues: 20
        tag-committer: false
        stale-branch-label: 'stale-branch'
        compare-branches: 'info'

    - name: Print stale/closed Branches
      id: print_cleanup_branches
      shell: bash
      env:
        BRANCHES: ${{ join(steps.cleanup_branches.outputs.*, ',') }}
      run: |
        echo "${BRANCHES}"
        if [ -f "${GITHUB_STEP_SUMMARY}" ]; then
          echo "${BRANCHES}" >> "${GITHUB_STEP_SUMMARY}"
        fi
